cw/urls.py
from django.urls import path
from .views import Homepage, News_List, News_Crawl, News_Page, News_Simliar, News_Detail

app_name = 'homepage'

urlpatterns = [
    path('', Homepage, name = 'Homepage'),
    path('crawling/', News_Crawl, name= 'crawling'),
    path('list/', News_List, name ='list'),
    path('list2/', News_Page, name = 'list2'),
    path('simliar/', News_Simliar, name = 'simliar'),
    path('detail/', News_Detail, name = 'detail')
]

pw/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Homepage/', include('cw.urls', namespace='homepage')),
]

templates/home.html
<h1> KBS 뉴스 크롤링 </h1>
<form action = "{% url 'homepage:list' %}" method = "POST">
    {% csrf_token %}
    {{k_w.as_p}}
    <label for = "kf"><label>
    <input type= "text" name='key_word'> <br><br>
    <button type = "submit">start crawling</button>
</form>
<br><br>
<!-- 뉴스를 가져오고 데이터를 저장할때 씀
<a href = "{% url 'homepage:crawling' %}" type ="submit"> 뉴스 스크롤하기 </a>
-->

templates/news_detail.html
<h1>{{ n_t }}</h1> <br>
{{n_m}}<br><br>

top 5 word<br> 
{% for a in t_w%}
{{forloop.counter}}. 
    {% for i in a%}
        {{i}}
    {% endfor%} <br>
{% endfor%}

<br><br>

simliar news : simliarity<br>
{% for i,n in s_l %}
{{forloop.counter}}.{{i}} : {{n|floatformat:"-3"}}%<br>

{% endfor %}
       
    

templates/news_list.html
<h1>검색한 단어와 관련된 뉴스</h1><br>
{% if board_list %}
{% for n in board_list %}
{{forloop.counter|add:n_p}}.{{n}}<br>
{% endfor %}
{%endif%}

<form action = "{% url 'homepage:simliar' %}" method = "POST">
    {% csrf_token %}
    {{k_w.as_p}}
    <label for = "kf"><label>
    <input type= "text" name='key_word'> <br><br>
    <button type = "submit">watch news</button>
</form>

<div style="text-align:center">
    <div class="pagination">
            
        <div style="width:35%; margin: 5px;">
            {% if board_list.has_previous %}
                <a class="abutton" href="?page=1">맨 앞으로</a>
                <a class="abutton" href="?page={{ board_list.previous_page_number }}">이전</a>
            {% endif %}
        </div>

        <div style="width:30%; margin: 5px;">
            {% for page in board_list.paginator.page_range %}
                {% if page >= board_list.number|add:-2 and page <= board_list.number|add:2 %}
                <span class="{% if page == board_list.number %}current{% endif %}">
                    <a href="?page={{ page }}">{{ page}}</a>
                </span>
                {% elif page >= board_list.number|add:-3 and page <= board_list.number|add:3 %}
                        ..
                {% endif %}
            {% endfor %}
        </div>

        <div style="width:35%; margin: 5px;">
            {% if board_list.has_next %}
                <a class="abutton" href="?page={{ board_list.next_page_number }}">다음</a>
                <a class="abutton" href="?page={{ board_list.paginator.num_pages }}">맨 뒤로</a>
            {% endif %}
        </div>
    </div>  
</div> 